plugins:
  # The first entry, which your test will read
  - name: FlexTable
    path: ""
    version: "1.0"
    DashboardURL: "/wp-admin/admin.php?page=gswpts-dashboard"
  
  # Example of another entry
  - name: WooCommerce
    path: ""
    version: "8.5"