plugins:
  # The first entry, which your test will read
  - name: WooCommerce
    path: ""
    version: "1.10.4.3"
    DashboardURL: "/wp-admin/admin.php?page=wc-admin"
  
  # Another entry, to test multiple entries
  - name: WP-Optimize - Clean, Compress, Cache
    path: ""
    version: "4.4.0"
    DashboardURL: "/wp-admin/admin.php?page=WP-Optimize"